version: "2"

services:

  arbitrage:
    container_name: arbitrage
    build:
      context: ./
      dockerfile: arbitrage.dockerfile
    command: python3 main.py
    volumes:
      - ./arbitrage_strategy:/arbitrage_strategy
